Bitfnity Node
bitfinity-network/reth pull request #1
Opened 2024-02-15 05:06 UTC by itsyaasir

2024-02-15 19:58 UTC, GraDKh approved these changes

2024-02-16 09:46 UTC, ufoscout requested changes
waiting for the changes we discussed offline

2024-02-16 09:59 UTC, F3kilo approved these changes

2024-02-19 09:07 UTC, ufoscout commented on bin/reth/src/commands/import.rs
> +        match tokio::signal::ctrl_c().await {
To be removed

2024-02-19 14:14 UTC, ufoscout approved these changes

2024-02-19 15:39 UTC, merged