Add workflow for deploying Bitfinity Reth to GCR
bitfinity-network/reth pull request #5
Opened 2024-02-20 10:14 UTC by itsyaasir

2024-02-20 10:25 UTC, ufoscout commented
@itsyaasir What about the workflow to publish the docker image as github package? Will it be part of another PR?

2024-02-20 10:54 UTC, itsyaasir commented
> @itsyaasir What about the workflow to publish the docker image as github package? Will it be part of another PR?

This is what the PR does

2024-02-20 11:08 UTC, ufoscout commented
> This is what the PR does

Ah! So it is not "gcr" but "gHcr" :)

2024-02-20 11:10 UTC, ufoscout requested changes
Please add instructions to use the docker image

2024-02-20 11:10 UTC, ufoscout commented on .github/workflows/publish.yml
> +name: 'Deploy Bitfinity Reth to GCR'
typo: GCR -> GHCR

2024-02-21 10:18 UTC, GraDKh approved these changes

2024-02-22 06:24 UTC, ufoscout approved these changes

2024-02-22 06:35 UTC, merged